### ISSUE TITLE
Getting the current position explicitly?

### ISSUE THREAD

**Issue by deviant-logic** [bos/attoparsec#101]
So I found myself pulling in `Data.Attoparsec.Internal.Types` and writing:

    getPos :: Parser Int
    getPos = AT.Parser $ \t pos more _ succ' -> succ' t pos more (AT.fromPos pos)

and it didn't seem like terribly unreasonable code.  (My use case is that I'm scanning git packfiles and I want to capture the file offset for each object I encounter).  Is this actually a terrible idea that can never work, or is it something you'd consider adding to the public attoparsec interface so I can feel slightly better about myself for pulling an `Internal` module?

I'm not trying to resurrect #16 or #19 (or anything else that's about automatically doing anything in particular on failure).  Apologies if I missed the point somewhere and this actually is a duplicate.  Thanks!

**Comment by bos** [comment]
It's not a terrible idea, but it ties us to a specific implementation that knows what the current position is. For example, until I rewrote attoparsec's internals, this was impossible to do.

If I added this, and then found an even better implementation strategy for the internals that once again made this impossible, it would be a big breaking change for people who depended on it.

Meanwhile, the fact that you can implement it by poking at the internals strikes a good middle ground, in my mind: you can do it, but you know you're in an uncomfortable state of sin :-)

**Comment by wdanilo** [comment]
@bos, since 3 years have passed and this is still possible, maybe its a good idea to add it to the public API? I know few projects (including one i'm currently working on), which depend exactly on this code. If in the future a new implementation strategy will appear then you can always release major version bump to Attoparsec with breaking API. For now however, this utility gives so much benefits that it should be available just by public API.
